### ISSUE TITLE
Hi Kuba, do you plan to add "delete" or "update" functions?

### ISSUE THREAD

**Issue by yjygit** [kuba--/zip#128]

**Comment by kuba--** [comment]
Hey @yjygit - Yes, I do.
But I believe some help is wanted, because I have to understand use cases and how it will extend an API.
`Delete/Update` functions will have to store entire zip in memory (in place operations) or use some temporary files, so I'm not sure what's better (have to think about it). Maybe adding both options is the solution.

On the other hand, lack of time is my main problem. I planned to add x64 support by updating miniz dependency, because I think this is  what should be done, first.

**Comment by maxsupermanhd** [comment]
Agreed, first of all - stable work and support

**Comment by kuba--** [comment]
Closing this one (so far) - `zip_delete_entries` API was added
