### ISSUE TITLE
zip_entry_open + windows

### ISSUE THREAD

**Issue by pavel-pimenov** [kuba--/zip#13]
zip_entry_open(zip, "EmoPacks/PeerWeb.xml"); - OK

zip_entry_open(zip, "EmoPacks\\PeerWeb.xml"); - Error

bug?

**Comment by kuba--** [comment]
Hey, are you trying to create a new archive or extract existing one?
Because for extracting it may not be related to OS, but how entry was named originally, e.g.: someone created an entry `EmoPacks/PeerWeb.xml` and you're trying to extract `EmoPacks\PeerWeb.xml`.
Anyway, maybe it's not a bad idea to _ignore/force/overwrite_ these separators per OS.
But it has to follow the standard and be compatible with other zip tools.

**Comment by kuba--** [comment]
Internally, zip stores forward slashes as required by the zip file specification, but externally it will match what is normally expected on a given platform.

**Comment by kuba--** [comment]
@pavel-pimenov I've pushed some changes to the branch:
https://github.com/kuba--/zip/tree/zip_entry_open/fix-13
Could you check if it works for you?
Thanks.

**Comment by kuba--** [comment]
the fix has been merged: https://github.com/kuba--/zip/pull/15
