### ISSUE TITLE
Upgrade to miniz 2.x ?

### ISSUE THREAD

**Issue by JCash** [kuba--/zip#144]
Hi!
Thanks for a great library!

Do you have any (near future) plans on updating to miniz version 2.x?

Regards,
Mathias

**Comment by kuba--** [comment]
> Hi!
> Thanks for a great library!

Thanks

> 
> Do you have any (near future) plans on updating to miniz version 2.x?
> 
Yes, would be great.
I've already tried to add support for _zip64_, but lack of spare time got me to the point where I didn't release anything ;(
Afaik, the latest version of _miniz_ also does not support _zip64_, but maybe it contains some bugfixes etc.

As always, any help is welcome ;)

**Comment by wdlkmpx** [comment]
I guess the way to upgrade to `miniz v2.1.0` is to produce patches to apply to that miniz.h version. I have no idea what has changed since 1.5, but I guess some major changes have happened and that will make things even harder.

But this commit (clang-format) cf20cef7133cbad52dda19990f1871a2ee780ff8
kind of makes the transition difficult

That commit kind of obfuscates everything specially for potential new contributors ...

**Comment by wdlkmpx** [comment]
It all started with miniz 1.15 r4

miniz.c 2013.10.14 https://github.com/richgel999/miniz/commit/28f5066e332590c8a68fa4870e89233e72ce7a44
miniz.h 2015.03.23 e5f376e4ee0f2a3b81a8d4680d510fcf166a0d5d

Exactly the same file. But zip's miniz.h contains a few extra macOS #defines

1.15r4 happens very early in miniz git history, basically everything happens after that.
The next commit splits the header into several files: https://github.com/richgel999/miniz/commit/724de0bb0f7612060c3ceafd556102dae0811390

At some point `amalgamate.sh` was added:
https://github.com/richgel999/miniz/blob/master/amalgamate.sh

Fast forward to miniz 2.1.0, now miniz is `miniz.c + miniz.h`, no longer a single header file
https://github.com/richgel999/miniz/releases/download/2.1.0/miniz-2.1.0.zip

From `220kb to 374kb`, the changes that happened look really big.

Here is the changelog, the revelant info is after v1.15 r4 STABLE ...
https://github.com/richgel999/miniz/blob/master/ChangeLog.md

**Comment by kuba--** [comment]
> It all started with miniz 1.15 r4
> 
> miniz.c 2013.10.14 [richgel999/miniz@28f5066](https://github.com/richgel999/miniz/commit/28f5066e332590c8a68fa4870e89233e72ce7a44)
> miniz.h 2015.03.23 [e5f376e](https://github.com/kuba--/zip/commit/e5f376e4ee0f2a3b81a8d4680d510fcf166a0d5d)
> 
> Exactly the same file. But zip's miniz.h contains a few extra macOS #defines
> 
> 1.15r4 happens very early in miniz git history, basically everything happens after that.
> The next commit splits the header into several files: [richgel999/miniz@724de0b](https://github.com/richgel999/miniz/commit/724de0bb0f7612060c3ceafd556102dae0811390)
> 
> At some point `amalgamate.sh` was added:
> https://github.com/richgel999/miniz/blob/master/amalgamate.sh
> 
> Fast forward to miniz 2.1.0, now miniz is `miniz.c + miniz.h`, no longer a single header file
> https://github.com/richgel999/miniz/releases/download/2.1.0/miniz-2.1.0.zip
> 
> From `220kb to 374kb`, the changes that happened look really big.
> 
> Here is the changelog, the revelant info is after v1.15 r4 STABLE ...
> https://github.com/richgel999/miniz/blob/master/ChangeLog.md

Single header file was made on purpose. 
Also to achieve what we have, right now, a little bit hacking was needed, so it's not as easy as copy-paste the file(s).

We have to make it as single header file (ideally), and walk through function by function to check what really changed.

**Comment by wdlkmpx** [comment]
If you browse the miniz source at 28f5066e332590c8a68fa4870e89233e72ce7a44 (git checkout ..)
miniz.c is exactly the same as the first miniz.h added to this project.

But there is amalgamation/miniz.c & amalgamation/miniz.h
What happened after that commit is that miniz.c was split into several files. So you're right, the amalgamation was always .c+.h,  but there was a .c file that was a single header or something.

I think miniz supports zip64, the changelog mentions zip64.

There have been many commits since 2.1.0, so maybe this time it could be a patchset to apply to miniz.c./h so that upgrading to the next version becomes easier, and retain the miniz.c/.h files as unchanged as possible (to produce diffs, only working with miniz releases).

I speculate that this might require a rewrite of many parts, the next version would be zip 0.2.

**Comment by SpaceIm** [comment]
It would be nice.
It would avoid duplicated symbols when a project indirectly depends on zip and miniz through static libs, since miniz 2.x is not a C header only lib (see this comment for an example of clashes: https://github.com/assimp/assimp/issues/3213#issuecomment-837584203).

**Comment by kuba--** [comment]
@SpaceIm - it was long time ago when I checked miniz 2.x, and definitivelly I'd like to do it, but I'm not sure if it's gonna solve your problem.
As far as I know you can also generate miniz 2.x as a single header file, but the reason why it was modified (but actually I didn't change existing stuff, mainly added some wrappers), is to be able expose _user friendly api_.
So, even if I upgrade to 2.x, it won't prevent compilation errors, if someone decides to use directly miniz in the same project.

**Comment by warmwaffles** [comment]
I was attempting to flip in miniz 2.0 hoping the change over would be simple. But simply put, it is not.

Some issues I ran into and don't know how it should be solved.

* `MZ_FILE_STAT_STRUCT`  is no longer present and there isn't any sort of replacement other than making one.
* Internal state for mz state is now opaque so a work around will be necessary.
* `MZ_MKDIR` is gone, a cross platform definition would need to be made. Not difficult.

Overall the real question is, should there be a larger refactor that takes place in order to make the transition to 2.0 or should I try to just shim in some fixes to get it compiling and functioning? I fear just shimming in fixes, would cause bugs.

**Comment by warmwaffles** [comment]
Actually, they offer a `BUILD_HEADER_ONLY` option that could be utilized and a largish portion of these issues would go away https://github.com/richgel999/miniz/blob/master/CMakeLists.txt#L72-L76

**Comment by warmwaffles** [comment]
That did it, the errors are much fewer, and easier to deal with. If I get this working, I'll submit a PR

**Comment by warmwaffles** [comment]
@kuba-- this is almost complete. The only thing that is failing is the permission test. Feel free to make edits how you see fit or suggestions.

**Comment by kuba--** [comment]
> @kuba-- this is almost complete. The only thing that is failing is the permission test. Feel free to make edits how you see fit or suggestions.

It also does not compile on windows.

**Comment by kuba--** [comment]
I'll take a look, but as far as I remember this upgrade requires some careful, step by step checks.
The new version of miniz uses some modified/extended structures, which are cached in `struct zip_t`. Also to make the API simple I added some helpers + permissions and custom crc32 function etc.

Anyway, thanks for PR, I'll take a look.

**Comment by kuba--** [comment]
PTAL on https://github.com/kuba--/zip/pull/203
So far, so good (all tests pass) - play with this branch and put some comments if it works for you.
Hopefully we can merge it asap.

**Comment by SpaceIm** [comment]
I'll see if I can bump `zip` conan recipe (called `kuba-zip`) to 0.2.0 with external `miniz` 2.2.0

**Comment by SpaceIm** [comment]
I see, it can't work, zip relies on internal details of miniz (not exposed in public API).

**Comment by kuba--** [comment]
@SpaceIm - what do you mean?
>  zip still relies on internal details of miniz (not exposed in public API).
This library is more or less _handy wrapper_ around miniz, so of course it will rely on miniz internals.
Btw., `master` branch (as well `miniz-2.2.0` branch) uses miniz v2.2.0.

**Comment by SpaceIm** [comment]
I would like to avoid ODR violation when miniz and zip are in the same dependency graph.

**Comment by kuba--** [comment]
> I would like to avoid ODR violation when miniz and zip are in the same dependency graph.

That would be perfect, but as you can see, all the handy stuff (like merging buffers into one entry etc.) are done by _hacking_ and/or _caching_ some miniz internals.
Otherwise, it's kind of pointless to use this library if we can directly use miniz.
