### ISSUE TITLE
How to split a file in different chunked files?

### ISSUE THREAD

**Issue by Sh0ckFR** [kuba--/zip#293]
Hello,

Actually I use this code to create a zip file:

```c
struct zip_t *zip = zip_open(ZIP_FILE_OUTPUT_NAME, ZIP_DEFAULT_COMPRESSION_LEVEL, 'w');
    {
        zip_entry_open(zip, OUTPUT_FILE);
        {
            zip_entry_fwrite(zip, OUTPUT_FILE);
        }
        zip_entry_close(zip);
    }
    zip_close(zip);
```

But I checked the different exemples and the source code, and I didn't find a way to create like 5 zip files to chunk my main zip file, is there something that I missing or this functionnality is not actually implemented?

Thank you for your help.

EDIT: I saw a similar issue, and I don't really want to merge my files, just have multiple chunked zip files

**Comment by kuba--** [comment]
If I understand correctly, ... for instance you have some `BIG_FILE`, which you want to compress. But instead of compressing that file as one zip entry, you want to create, e.g. 5 zip archives where each zip entry will keep compressed chunk of that `BIG_FILE`.
If this is correct, there is no _automagic_ API which will do it for you.

You have to manually create those archives and kind of _manually_ split the `BIG_FILE`.
Instead of using `...fwrite`, use `...write` where you pass a `buffer` and `buffer size`. Actually, under the hood this is what `fwrite` does:
```c
//...
  if (!(stream = MZ_FOPEN(filename, "rb"))) {
    // Cannot open filename
    return ZIP_EOPNFILE;
  }

  while ((n = fread(buf, sizeof(mz_uint8), MZ_ZIP_MAX_IO_BUF_SIZE, stream)) >  0) {
    if (zip_entry_write(zip, buf, n) < 0) {
      err = ZIP_EWRTENT;
      break;
    }
  }
  fclose(stream);
```

**Comment by Sh0ckFR** [comment]
Thank you, problem solved, have a nice day!
