### ISSUE TITLE
SonarQube security hotspot

### ISSUE THREAD

**Issue by TheSlackOne** [kuba--/zip#294]
Hello!, our SonarQube reports `zip_open` call to be a potencial security hotspot (severity low). I believe it might be a common issue that could be solved by passing a flag, but I couldn't find how.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/13991630/234403422-cc2c16e1-060b-490b-a991-78150fb74f5b.png">

**Comment by kuba--** [comment]
How do you understand this warning?

In my honest opinion it's not related to `zip_open`. It's about, how someone can compress e.g. GB of _zeros_ what can end up with very tiny zip archive but after unziping it's full of garbage.

So, be careful how/where do you compress your data, but it's not related to this particular call.
Moreover, in your example, you're compressing data, you're passing `inFile`s, so it's your app responsibility to check if these files are garbage, or not.

**Comment by TheSlackOne** [comment]
Yes, agree, and it is trusted data. I just wonder if I could do something from the `zip_open()` call, like passing a flag, to avoid the security hotspot warning.

**Comment by kuba--** [comment]
No, because this warning is very informative/generic.
SonarQuebe didn't analyze the zip library, just posted some _info_ related to zip archives from DB (the same stuff you can find for some PHP library: https://rules.sonarsource.com/php/RSPEC-5042).

I would recommend to try _real_ static analysis tools, like cpp-check, infer, clang static analysis or PVS studio.

**Comment by TheSlackOne** [comment]
Thank you, Kuba, I appreciate your input.
