### ISSUE TITLE
UTF8 File Name Support on Windows Platform

### ISSUE THREAD

**Issue by webfolderio** [kuba--/zip#39]
Hi,

On windows platform non-ascii file names created incorrectly.
miniz use fopen_s and freopen_s to create and redirect the pre-opened files.
It might be better to use _wfopen_s and _wfreopen_s methods which supports wchar.

Also zip.c (line 548)  use fopen to read files. Its better to replace it with _wfopen_s

Thanks

**Comment by kuba--** [comment]
@webfolderio - `zip` is a platform independent library so we have to figure out a general solution. Moreover `wchar_t` will not solve the problem because many _zip_ tools/libraries implement unicode differently for each OS. Also please, take a look here: https://github.com/kuba--/zip/issues/26 where we had a short discussion with @ZSaberLv0 about _unicode file names in zip content_. There is a link to pretty interesting blog post: https://marcosc.com/2008/12/zip-files-and-encoding-i-hate-you/

Last but not least, at the end you have to convert `wchar_t` to/from `char`, because not all functions are available on all Operating Systems, e.g.: `wfopen`.
```c
FILE *wfopen(const wchar_t *path, const wchar_t *mode) {
    FILE *f = NULL;
#if defined(_WIN32) || defined(_MSC_VER)
    return _wfopen(path, mode);
#else
    char filepath[ENCODE_MAX_SIZE] = { 0 };
    wcstombs(filepath, path, ENCODE_MAX_SIZE);
    char cmode[ENCODE_MAX_SIZE] = { 0 };
    wcstombs(cmode, mode, ENCODE_MAX_SIZE);
    return fopen(filepath, cmode);
#endif
}
```

And if you need to directly convert `char` to/from `wchar_t` on windows then most likely you have to use C++ functions: 
`size_t size = MultiByteToWideChar(CP_UTF8, 0, bytes, -1, NULL, 0);`
or
`size_t size = WideCharToMultiByte(CP_UTF8, 0, bytes, -1, NULL, 0, NULL, NULL);`

and do not forget that settings (set locale) are also very important.

So, to recap - if you need unicode support in your app maybe the easiest way is to implement a type converters, e.g. (this is what I used in the past):
```c
wchar_t *char2wchar(char *bytes) {
    if(!bytes)
        return NULL;
#if defined(_WIN32) || defined(_MSC_VER)
    size_t size = MultiByteToWideChar(CP_UTF8, 0, bytes, -1, NULL, 0);
    if(!size)
        return NULL;
    wchar_t *res_wstr = (wchar_t *)calloc(size + 1, sizeof(wchar_t));
    if(!res_wstr)
        return NULL;
    if(!MultiByteToWideChar(CP_UTF8, 0, bytes, -1, res_wstr, size)) {
        free(res_wstr); res_wstr = NULL;
        return NULL;
    }
    return res_wstr;
#else
    wchar_t *res_wstr = (wchar_t *)calloc(ENCODE_MAX_SIZE + 1, sizeof(wchar_t));
    if(!res_wstr)
        return NULL;
    if(mbstowcs(res_wstr, bytes, ENCODE_MAX_SIZE) == (size_t)-1) {
        free(res_wstr); res_wstr = NULL;
        return NULL;
    }
    return res_wstr;
#endif
}

char *wchar2char(wchar_t *bytes) {
    if(!bytes)
        return NULL;
#if defined(_WIN32) || defined(_MSC_VER)
    size_t size = WideCharToMultiByte(CP_UTF8, 0, bytes, -1, NULL, 0, NULL, NULL);
    if(!size)
        return NULL;
    char *res_str = (char *)calloc(size + 1, sizeof(char));
    if(!res_str)
        return NULL;
    if(!WideCharToMultiByte(CP_UTF8, 0, bytes, -1, res_str, size, NULL, NULL)) {
        free(res_str); res_str = NULL;
        return NULL;
    }
    return res_str;
#else
    char *res_str = (char *)calloc(ENCODE_MAX_SIZE + 1, sizeof(char));
    if(!res_str)
        return NULL;
    if(wcstombs(res_str, bytes, ENCODE_MAX_SIZE) == (size_t)-1) {
        free(res_str); res_str = NULL;
        return NULL;
    }
    return res_str;
#endif
}
```

Thanks, kuba--
