### ISSUE TITLE
zip_entry_noallocread() should return amount of bytes read

### ISSUE THREAD

**Issue by KristupasSavickas** [kuba--/zip#75]
`zip_entry_noallocread()` should return the amount of bytes read, just like the `read()` syscall. If this gets implemented, a return type of `ssize_t` might be more appropriate.

**Comment by kuba--** [comment]
@KristupasSavickas - ok, makes sense for read functions. I'll change it to:
>  If successful, the number of bytes actually read is returned, otherwise, a -1 is returned to indicate the error.

**Comment by KristupasSavickas** [comment]
Would it be possible to only read `bufsize` amount of bites and maybe even specify an offset so that files could be read in parts?

**Comment by kuba--** [comment]
@KristupasSavickas - I dived into `tinfl_decompress` function. For `zip_entry_noallocread` we need to first read a compressed stream and decompress it.
So we read _N_ bytes (max 64K) and then decompress, but it's hard to predict what size will be the output. Moreover not to loose to much memory output buffer's size should be a power of 2.
So that's why `zip_entry_noallocread` requires a buffer as large as uncompressed stream, because we know what is the size of uncompressed entry, but hard to say what will be the size of the chunk.
Of course we can read byte by byte and check of uncompressed size is `>= bufsize` but it will extremely slow down decompression.
So I wonder if it makes sense if under the hood we'll allocate output buffer for needed size (uncompressed size) and at the end `memcpy` to the output buffer. Generally what is  required now, can be be hidden but less efficient because of extra `memcpy`.

**Comment by kuba--** [comment]
@KristupasSavickas - some silly prototype you can find here: https://github.com/kuba--/zip/pull/77
Please let me know if it works for you, so can add similar function.
