### ISSUE TITLE
miniz.h upgrade

### ISSUE THREAD

**Issue by MXWXZ** [kuba--/zip#94]
I found the miniz.h now we are using is v1.15, it's too old and may have bugs (newest version is 2.0.8).

Do we have a plan to upgrade it? Or, is it safe that I just upgrade the miniz.h without changing any codes in  zip.h?

It changes from v1.x to v2.x so I want to confirm. I'm not familiar with zlib & miniz low-level API :( 
But this library is ez to use.

**Comment by kuba--** [comment]
@MXWXZ - to keep super simple API, I had to hack the `miniz` a little bit. Also as you can see I've minimized it.
In other words, it to upgrade `miniz` it's not just copy-pasting new files.
So far, it was easier to fix bugs in local copy instead of relying on 3rd party.

Is there any feature which you really need and it's not in the current version of miniz?
Of course, you can try to upgrade and send PR - would be great, thanks.

**Comment by MXWXZ** [comment]
OK, I just wonder if there are some potential bugs in the current version (It works well so far).
Anyway, thanks for the work to simplify the API 👍

**Comment by kuba--** [comment]
@MXWXZ - I went briefly through changes and I don't see any significant bug fixes. The main change in ver 2.X is a new API `_v2`.
If you are OK with this, we may close this issue.

Btw. I'm getting feedback, so I'm curious, where/how do you use this library ;-)

**Comment by MXWXZ** [comment]
Oh I'm writting a program on my Raspberry Pi, zlib is too complex to use and other library I found could only work on Windows or too heavy...
This repo is light-weighted so I like it :)
